@set ADVISOR_XE_2016_DIR=C:\Program Files (x86)\IntelSWTools\Advisor XE 2016\
@set ADVIXE_LANG=en
@set ALLUSERSPROFILE=C:\ProgramData
@set AMPLXE_LANG=en
@set APPDATA=C:\Users\Dmitri\AppData\Roaming
@set CommandPromptType=Native
@set CommonProgramFiles=C:\Program Files\Common Files
@set CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
@set CommonProgramW6432=C:\Program Files\Common Files
@set COMPUTERNAME=ARBOREA
@set ComSpec=C:\WINDOWS\system32\cmd.exe
@set CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
@set CUDA_PATH_V7_5=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
@set CUDA_PATH_V8_0=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
@set DNX_HOME=%USERPROFILE%\.dnx
@set FACADES_4.5=C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades
@set FACADES_4.5.1=C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Facades
@set FACADES_4.5.2=C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades
@set FACADES_4.6=C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades
@set FACADES_4.6.1=C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\Facades
@set FACADES_4.6.2=C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\Facades
@set FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
@set FPS_BROWSER_USER_PROFILE_STRING=Default
@set Framework40Version=v4.0
@set FrameworkDir=C:\WINDOWS\Microsoft.NET\Framework64
@set FrameworkDIR64=C:\WINDOWS\Microsoft.NET\Framework64
@set FrameworkVersion=v4.0.30319
@set FrameworkVersion64=v4.0.30319
@set FSHARPINSTALLDIR=C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\
@set HOMEDRIVE=C:
@set HOMEPATH=\Users\Dmitri
@set ICPP_COMPILER16=C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2016.3.207\windows\
@set IFORT_COMPILER16=C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2016.3.207\windows\
@set include=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt;C:\Program Files (x86)\IntelSWTools\Trace Analyzer and Collector\9.1.2.024\include
@set INSPECTOR_XE_2016_DIR=C:\Program Files (x86)\IntelSWTools\Inspector XE 2016\
@set INSPXE_LANG=en
@set INTEL_DEV_REDIST=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\
@set INTEL_LICENSE_FILE=C:\Program Files (x86)\Common Files\\Intel\Licenses;C:\Program Files (x86)\Common Files\Intel\Licenses
@set I_MPI_ROOT=C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2016.3.207\windows\mpi
@set LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\um\x64;
@set LIBPATH=C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\UnionMetadata;C:\Program Files (x86)\Windows Kits\10\References;\Microsoft.VCLibs\14.0\References\CommonConfiguration\neutral;
@set LM_LICENSE_FILE=c:\temp\license.dat
@set LOCALAPPDATA=C:\Users\Dmitri\AppData\Local
@set LOGONSERVER=\\ARBOREA
@set MIC_LD_LIBRARY_PATH=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\compiler\lib\intel64_win_mic
@set MSBuildLoadMicrosoftTargetsReadOnly=true
@set NETFXSDKDir=C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\
@set NIEXTCCOMPILERSUPP=C:\Program Files (x86)\National Instruments\Shared\ExternalCompilerSupport\C\
@set NUMBER_OF_PROCESSORS=8
@set NVCUDASAMPLES7_5_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v7.5
@set NVCUDASAMPLES8_0_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v8.0
@set NVCUDASAMPLES_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v8.0
@set NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
@set OneDrive=C:\Users\Dmitri\OneDrive
@set OS=Windows_NT
@set Path=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\MSBuild\14.0\bin\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\NativeBinaries\x86;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\libnvvp;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\libnvvp;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\IntelSWTools\Trace Analyzer and Collector\9.1.2.024\bin;C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2016.3.207\windows\mpi\intel64\bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\mpirt;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32_win\mpirt;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32_win\compiler;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\Dmitri\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\TortoiseHg\;C:\Program Files\TortoiseGit\bin;C:\Program Files\MATLAB\R2016a\runtime\win64;C:\Program Files\MATLAB\R2016a\bin;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files (x86)\Pandoc\;C:\Program Files (x86)\LyX 2.2\Perl\bin;C:\Anaconda2;C:\Anaconda2\Scripts;C:\Anaconda2\Library\bin;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\dotnet\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files (x86)\IntelSWTools\Trace Analyzer and Collector\9.1.2.024\dll;C:\Users\Dmitri\.dnx\bin;C:\Users\Dmitri\AppData\Local\Microsoft\WindowsApps;;C:\altera\13.0sp1\modelsim_ase\win32aloem;C:\Program Files (x86)\Microsoft VS Code\bin
@set PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
@set PkgDefApplicationConfigFile=C:\Users\Dmitri\AppData\Local\Microsoft\VisualStudio\14.0\devenv.exe.config
@set Platform=X64
@set PROCESSOR_ARCHITECTURE=AMD64
@set PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
@set PROCESSOR_LEVEL=6
@set PROCESSOR_REVISION=5e03
@set ProgramData=C:\ProgramData
@set ProgramFiles=C:\Program Files
@set ProgramFiles(x86)=C:\Program Files (x86)
@set ProgramW6432=C:\Program Files
@set PROMPT=$P$G
@set PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
@set PUBLIC=C:\Users\Public
@set QUARTUS_ROOTDIR=C:\altera\13.0sp1\quartus
@set SESSIONNAME=Console
@set SOPC_KIT_NIOS2=C:\altera\13.0sp1\nios2eds
@set SystemDrive=C:
@set SystemRoot=C:\WINDOWS
@set TEMP=C:\Users\Dmitri\AppData\Local\Temp
@set TMP=C:\Users\Dmitri\AppData\Local\Temp
@set UCRTVersion=10.0.14393.0
@set UniversalCRTSdkDir=C:\Program Files (x86)\Windows Kits\10\
@set USERDOMAIN=ARBOREA
@set USERDOMAIN_ROAMINGPROFILE=ARBOREA
@set USERNAME=Dmitri
@set USERPROFILE=C:\Users\Dmitri
@set VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
@set VisualStudioDir=C:\Users\Dmitri\Documents\Visual Studio 2015
@set VisualStudioEdition=Microsoft Visual Studio Enterprise 2015
@set VisualStudioVersion=14.0
@set VS120COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\
@set VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
@set VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio 14.0\
@set VSLANG=1033
@set VSSDK140Install=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VSSDK\
@set VTUNE_AMPLIFIER_XE_2016_DIR=C:\Program Files (x86)\IntelSWTools\VTune Amplifier XE 2016\
@set VT_ADD_LIBS=ws2_32.lib advapi32.lib
@set VT_DLL_DIR=C:\Program Files (x86)\IntelSWTools\Trace Analyzer and Collector\9.1.2.024\dll
@set VT_FMPI_DLL=impi.dll
@set VT_LIB_DIR=C:\Program Files (x86)\IntelSWTools\Trace Analyzer and Collector\9.1.2.024\lib
@set VT_MPI=impi64
@set VT_MPI_DLL=impi.dll
@set VT_ROOT=C:\Program Files (x86)\IntelSWTools\Trace Analyzer and Collector\9.1.2.024\
@set VT_SLIB_DIR=C:\Program Files (x86)\IntelSWTools\Trace Analyzer and Collector\9.1.2.024\dll
@set VXIPNPPATH=C:\Program Files (x86)\IVI Foundation\VISA\
@set windir=C:\WINDOWS
@set WindowsLibPath=C:\Program Files (x86)\Windows Kits\10\UnionMetadata;C:\Program Files (x86)\Windows Kits\10\References
@set WindowsSdkDir=C:\Program Files (x86)\Windows Kits\10\
@set WindowsSDKLibVersion=10.0.14393.0\
@set WindowsSDKVersion=10.0.14393.0\
@set WindowsSDK_ExecutablePath_x64=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\
@set WindowsSDK_ExecutablePath_x86=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\
@set WIX=C:\Program Files (x86)\WiX Toolset v3.11\
@set __COMPAT_LAYER=DetectorsWin8

@call "C:\Program Files (x86)\PVS-Studio\x64\clang.exe" @"C:\Dropbox\Projects\Commercial\Bloom\src\Bloom\ShaderUtils.cpp.PVS-Studio.preprocess.cmd.rsp" 2>&1